version: 0.2

env:
  parameter-store:
    REGION_NAME: /tenet/$ENV/region_name

phases:
  install:
    runtime-versions:
      nodejs: 16

  build:
    commands:
      - cd backend/
      - echo "Removing old environment variable file"
      - rm -rf .env
      - sh create-environment-variables.sh
      - cat .env
      - echo "Installing serverless framework"
      - npm i --silent --no-progress -g serverless@3.21.0
      - echo "Installing packages"
      - npm i
      - echo "Installed packages successfully"

  post_build:
    commands:
      - echo "Deploying serverless"
      - ls -al
      - serverless deploy -s $ENV -r $REGION_NAME --verbose
      - echo "Deployed serverless successfully"

cache:
  paths:
    - '/backend/**/*'      
