{{- if .Values.ingress.enabled -}}
{{- $fullName := include "soc-backend-api.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
{{ include "soc-backend-api.labels" . | indent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host | quote }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ . }}
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ $fullName }}
            port:
              name: http
      {{- end }}
  {{- end }}
{{- end }}
