apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
type: Opaque
data:
  mysql_password: {{ .Values.mysql_password | b64enc | quote }}
  smtp_password: {{ .Values.smtp_password | b64enc | quote }}
  AWS_ACCESS_KEY: {{ .Values.AWS_ACCESS_KEY | b64enc | quote }}
  AWS_SECRET_KEY: {{ .Values.AWS_SECRET_KEY | b64enc | quote }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.KEYCLOAK_ADMIN_PASSWORD | b64enc | quote }}
  DAILYBEAST_AWS_ACCESS_KEY: {{ .Values.DAILYBEAST_AWS_ACCESS_KEY | b64enc | quote }}
  DAILYBEAST_AWS_SECRET_KEY: {{ .Values.DAILYBEAST_AWS_SECRET_KEY | b64enc | quote }}

