apiVersion: v1
kind: Service
metadata:
  name: {{ include "soc-backend-api.fullname" . }}
  labels:
{{ include "soc-backend-api.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.http.port }}
      nodePort: {{ .Values.service.http.nodePort }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "soc-backend-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
